[package]
edition = "2021"
name = "alphametics"
version = "1.3.0"

[lib]
name = "alphametics"
path = "src/lib.rs"

[[bin]]

name = "alphametics"
path = "src/bin.rs"

[dependencies]
itertools = "0.10.5"
permutator = "0.4.3"
